// Mock data for FlowOS - AI Business Operating System
// Realistic construction company data

export const companyInfo = {
  name: "Meridian Construction Group",
  tagline: "Building Tomorrow, Today",
  healthScore: 87,
  industry: "Construction & Engineering",
};

export const currentUser = {
  id: "u1",
  name: "Arjay Delos Santos",
  role: "CEO",
  avatar: "AD",
  email: "arjay_ds@flowos.com",
};

export const kpis = {
  revenue: { value: 4280000, change: +12.4, period: "MTD" },
  expenses: { value: 2940000, change: +3.2, period: "MTD" },
  profit: { value: 1340000, change: +24.1, period: "MTD" },
  cashFlow: { value: 890000, change: -2.1, period: "MTD" },
  activeProjects: 18,
  atRisk: 3,
  tasksToday: 24,
  pendingApprovals: 7,
  unreadMessages: 34,
  aiSuggestions: 12,
};

export const revenueData = [
  { month: "Jan", revenue: 3200000, expenses: 2400000, profit: 800000 },
  { month: "Feb", revenue: 3600000, expenses: 2600000, profit: 1000000 },
  { month: "Mar", revenue: 3100000, expenses: 2300000, profit: 800000 },
  { month: "Apr", revenue: 3900000, expenses: 2700000, profit: 1200000 },
  { month: "May", revenue: 4100000, expenses: 2850000, profit: 1250000 },
  { month: "Jun", revenue: 4280000, expenses: 2940000, profit: 1340000 },
];

export const cashFlowData = [
  { week: "W1", inflow: 1200000, outflow: 980000 },
  { week: "W2", inflow: 1450000, outflow: 1100000 },
  { week: "W3", inflow: 980000, outflow: 1200000 },
  { week: "W4", inflow: 1680000, outflow: 1040000 },
];

export const customers = [
  {
    id: "c1",
    name: "Nexus Property Group",
    contact: "David Kim",
    email: "d.kim@nexusproperty.com",
    phone: "+1 (555) 201-4892",
    status: "active",
    healthScore: 92,
    totalValue: 12400000,
    projects: 4,
    avatar: "NP",
    type: "Corporate",
    since: "2021-03-15",
    location: "Austin, TX",
    aiSummary: "High-value client with consistent project delivery. Recently approved Phase 3 of the downtown complex. No payment delays in 3 years.",
    tags: ["premium", "residential", "commercial"],
  },
  {
    id: "c2",
    name: "Harborview Developments",
    contact: "Sarah Chen",
    email: "s.chen@harborview.com",
    phone: "+1 (555) 347-9201",
    status: "active",
    healthScore: 78,
    totalValue: 8700000,
    projects: 3,
    avatar: "HD",
    type: "Developer",
    since: "2022-07-10",
    location: "Seattle, WA",
    aiSummary: "Mid-tier developer with growing portfolio. Payment delays on last invoice require attention. Strong pipeline for Q3.",
    tags: ["waterfront", "residential"],
  },
  {
    id: "c3",
    name: "GreenState Infrastructure",
    contact: "Robert Osei",
    email: "r.osei@greenstate.gov",
    phone: "+1 (555) 883-5510",
    status: "active",
    healthScore: 95,
    totalValue: 22000000,
    projects: 2,
    avatar: "GS",
    type: "Government",
    since: "2020-01-08",
    location: "Denver, CO",
    aiSummary: "Government client - highest value in portfolio. Strict compliance requirements met. RFP for bridge project due Aug 15.",
    tags: ["government", "infrastructure", "bridge"],
  },
  {
    id: "c4",
    name: "Pinnacle Hotels LLC",
    contact: "Amanda Torres",
    email: "a.torres@pinnaclehotels.com",
    phone: "+1 (555) 429-7753",
    status: "at-risk",
    healthScore: 45,
    totalValue: 5200000,
    projects: 1,
    avatar: "PH",
    type: "Hospitality",
    since: "2023-02-20",
    location: "Miami, FL",
    aiSummary: "At-risk: Outstanding invoice $340K, 47 days overdue. Project timeline slipped by 3 weeks. Recommend executive outreach.",
    tags: ["hospitality", "renovation"],
  },
  {
    id: "c5",
    name: "TechPark Realty Trust",
    contact: "James Whitfield",
    email: "j.whitfield@techparkrealty.com",
    phone: "+1 (555) 671-2284",
    status: "active",
    healthScore: 88,
    totalValue: 15800000,
    projects: 5,
    avatar: "TR",
    type: "REIT",
    since: "2021-09-14",
    location: "San Jose, CA",
    aiSummary: "Tech sector client expanding rapidly. 2 new projects pending contract signature. Preferred contractor status since 2022.",
    tags: ["tech-campus", "commercial", "preferred"],
  },
];

export const projects = [
  {
    id: "p1",
    name: "Downtown Mixed-Use Tower",
    customer: "Nexus Property Group",
    customerId: "c1",
    status: "in-progress",
    progress: 68,
    budget: 8400000,
    spent: 5712000,
    startDate: "2024-01-15",
    endDate: "2025-03-30",
    pm: "Carlos Rivera",
    risk: "medium",
    phase: "Structural",
    location: "Austin, TX",
    description: "40-story mixed-use development with 280 residential units and 60,000 sqft commercial space",
    tasks: 142,
    completedTasks: 96,
    team: ["Carlos Rivera", "Jenny Park", "Mike Thompson", "Aisha Williams"],
    aiInsight: "Concrete delivery delays on floors 28-32 may impact critical path by 8-12 days. Recommend sourcing alternative supplier.",
  },
  {
    id: "p2",
    name: "Harborview Marina Complex",
    customer: "Harborview Developments",
    customerId: "c2",
    status: "at-risk",
    progress: 34,
    budget: 4200000,
    spent: 1890000,
    startDate: "2024-03-01",
    endDate: "2025-01-15",
    pm: "Jenny Park",
    risk: "high",
    phase: "Foundation",
    location: "Seattle, WA",
    description: "Premium marina complex with 120 boat slips, clubhouse, and waterfront residential units",
    tasks: 89,
    completedTasks: 30,
    team: ["Jenny Park", "Tom Bradley", "Rachel Kim"],
    aiInsight: "3 critical path tasks are 11 days behind. Weather delays and permit issues detected. Budget overrun risk: 23%.",
  },
  {
    id: "p3",
    name: "I-70 Highway Interchange",
    customer: "GreenState Infrastructure",
    customerId: "c3",
    status: "in-progress",
    progress: 82,
    budget: 18500000,
    spent: 15170000,
    startDate: "2023-06-01",
    endDate: "2025-09-30",
    pm: "Robert Chen",
    risk: "low",
    phase: "Paving",
    location: "Denver, CO",
    description: "Full reconstruction of I-70/US-6 interchange including 4 new ramps and bridge widening",
    tasks: 280,
    completedTasks: 229,
    team: ["Robert Chen", "Diana Walsh", "Frank Ortiz", "Yuki Tanaka"],
    aiInsight: "On track for early completion. Cost savings of $840K identified in materials. Final inspection scheduled for Aug 12.",
  },
  {
    id: "p4",
    name: "Pinnacle Resort Renovation",
    customer: "Pinnacle Hotels LLC",
    customerId: "c4",
    status: "delayed",
    progress: 41,
    budget: 5200000,
    spent: 2756000,
    startDate: "2024-02-10",
    endDate: "2024-11-30",
    pm: "Sofia Nguyen",
    risk: "high",
    phase: "Interior Fit-out",
    location: "Miami, FL",
    description: "Full renovation of 8-story luxury resort including lobby, 240 rooms, spa, and restaurant",
    tasks: 164,
    completedTasks: 67,
    team: ["Sofia Nguyen", "Alex Grant", "Maria Santos"],
    aiInsight: "CRITICAL: Timeline delayed 3 weeks due to custom furniture supplier insolvency. Immediate escalation required.",
  },
  {
    id: "p5",
    name: "TechPark Phase 4 Campus",
    customer: "TechPark Realty Trust",
    customerId: "c5",
    status: "in-progress",
    progress: 56,
    budget: 12000000,
    spent: 6720000,
    startDate: "2024-04-01",
    endDate: "2025-06-30",
    pm: "Marcus Webb",
    risk: "low",
    phase: "MEP Installation",
    location: "San Jose, CA",
    description: "3-building tech campus with 450,000 sqft office space, data center, and employee amenities",
    tasks: 218,
    completedTasks: 122,
    team: ["Marcus Webb", "Priya Sharma", "Kevin Liu"],
    aiInsight: "MEP coordination on track. Solar panel installation approved ahead of schedule. LEED Platinum certification likely.",
  },
];

export const tasks = [
  {
    id: "t1",
    title: "Review structural drawings for Tower floors 28-32",
    description: "Engineering review required before concrete pour can proceed. Check load calculations and rebar specifications.",
    priority: "urgent",
    status: "pending",
    deadline: "2024-06-25",
    project: "Downtown Mixed-Use Tower",
    projectId: "p1",
    customer: "Nexus Property Group",
    assignee: "Carlos Rivera",
    dependencies: ["t4"],
    aiSuggestion: "Two similar drawing reviews in 2023 took 3-4 days. Recommend assigning additional structural engineer to accelerate.",
    category: "Engineering",
  },
  {
    id: "t2",
    title: "Generate monthly progress report - Marina Complex",
    description: "Client requires monthly update on construction progress, budget status, and risk register.",
    priority: "high",
    status: "ai-ready",
    deadline: "2024-06-28",
    project: "Harborview Marina Complex",
    projectId: "p2",
    customer: "Harborview Developments",
    assignee: "Jenny Park",
    dependencies: [],
    aiSuggestion: "Report draft ready for review. AI has compiled data from 34 sources. Estimated review time: 15 minutes.",
    category: "Reporting",
  },
  {
    id: "t3",
    title: "Procure alternative concrete supplier",
    description: "Current supplier unable to fulfill floors 28-32 delivery. Need to source certified alternative within 48 hours.",
    priority: "urgent",
    status: "in-progress",
    deadline: "2024-06-24",
    project: "Downtown Mixed-Use Tower",
    projectId: "p1",
    customer: "Nexus Property Group",
    assignee: "Mike Thompson",
    dependencies: [],
    aiSuggestion: "Found 3 pre-qualified suppliers within 50km. Summit Concrete has availability and price match. Contact: (555) 889-2341.",
    category: "Procurement",
  },
  {
    id: "t4",
    title: "Safety inspection - Highway interchange bridge section",
    description: "Monthly safety compliance inspection for bridge widening section. Required before next pour.",
    priority: "high",
    status: "scheduled",
    deadline: "2024-06-26",
    project: "I-70 Highway Interchange",
    projectId: "p3",
    customer: "GreenState Infrastructure",
    assignee: "Diana Walsh",
    dependencies: [],
    aiSuggestion: "Previous 3 inspections all passed first time. Checklist pre-populated from historical data.",
    category: "Safety",
  },
  {
    id: "t5",
    title: "Escalate Pinnacle Resort timeline with client",
    description: "3-week delay requires formal client communication and contract amendment discussion.",
    priority: "urgent",
    status: "pending",
    deadline: "2024-06-23",
    project: "Pinnacle Resort Renovation",
    projectId: "p4",
    customer: "Pinnacle Hotels LLC",
    assignee: "Sofia Nguyen",
    dependencies: [],
    aiSuggestion: "AI has drafted escalation email and change order document. Risk of contract penalty clause if not addressed within 72hrs.",
    category: "Client Relations",
  },
];

export const inboxItems = [
  {
    id: "i1",
    type: "email",
    sender: "David Kim",
    senderCompany: "Nexus Property Group",
    subject: "RE: Phase 3 Schedule Acceleration Request",
    preview: "Following our conversation, we'd like to explore options to accelerate the structural phase by 3-4 weeks if feasible...",
    time: "09:42 AM",
    priority: "high",
    aiSummary: "Client requesting phase acceleration. Timeline feasibility analysis needed. Budget impact estimated $120K-180K.",
    suggestedActions: ["Schedule call", "Prepare feasibility report", "Review resource availability"],
    project: "Downtown Mixed-Use Tower",
    confidence: 94,
    read: false,
  },
  {
    id: "i2",
    type: "whatsapp",
    sender: "Carlos Rivera",
    senderCompany: "Internal",
    subject: "Concrete delivery status update",
    preview: "The Summit Concrete rep confirmed they can deliver floors 28-32 materials by Tuesday. Price is 4% above budget...",
    time: "08:15 AM",
    priority: "urgent",
    aiSummary: "Concrete alternative found. 4% above budget. Needs approval to proceed. Time-sensitive: delivery slot expires in 6 hours.",
    suggestedActions: ["Approve procurement", "Request price negotiation", "Review alternatives"],
    project: "Downtown Mixed-Use Tower",
    confidence: 97,
    read: false,
  },
  {
    id: "i3",
    type: "meeting",
    sender: "AutoScheduler",
    senderCompany: "Internal AI",
    subject: "Meeting Summary: Site Review - TechPark Phase 4",
    preview: "Transcript from yesterday's 2-hour site review meeting. Key decisions: Solar panel installation approved for Q3...",
    time: "Yesterday",
    priority: "medium",
    aiSummary: "5 action items extracted. 2 decisions recorded. Next meeting scheduled for July 5. All items added to task queue.",
    suggestedActions: ["Review summary", "Assign action items", "Update project board"],
    project: "TechPark Phase 4 Campus",
    confidence: 91,
    read: true,
  },
  {
    id: "i4",
    type: "invoice",
    sender: "BuilderMart Supply Co",
    senderCompany: "Vendor",
    subject: "Invoice #BM-2024-8821 - Materials Delivery",
    preview: "Invoice for steel reinforcement delivery to Harborview site. Amount: $284,500. Due: July 15, 2024...",
    time: "Yesterday",
    priority: "medium",
    aiSummary: "Invoice matches PO #4492. Price variance: +2.1% vs contract. Within approved tolerance. Recommend approval.",
    suggestedActions: ["Approve payment", "Flag variance", "Request credit note"],
    project: "Harborview Marina Complex",
    confidence: 88,
    read: true,
  },
  {
    id: "i5",
    type: "notification",
    sender: "AI Risk Monitor",
    senderCompany: "FlowOS",
    subject: "Risk Alert: Pinnacle Resort - Payment Default Risk",
    preview: "Customer payment analysis indicates elevated default risk. Outstanding: $340K (47 days overdue). Credit score: B-...",
    time: "2 hours ago",
    priority: "urgent",
    aiSummary: "Financial risk alert. Recommend stopping work if not paid within 5 days per contract clause 14.2. Legal review suggested.",
    suggestedActions: ["Review contract", "Initiate collections", "Escalate to CEO"],
    project: "Pinnacle Resort Renovation",
    confidence: 82,
    read: false,
  },
];

export const documents = [
  {
    id: "doc1",
    name: "Downtown Tower - Structural Engineering Package v4.2",
    type: "pdf",
    size: "24.8 MB",
    uploadedBy: "Carlos Rivera",
    uploadedAt: "2024-06-20",
    project: "Downtown Mixed-Use Tower",
    customer: "Nexus Property Group",
    tags: ["structural", "drawings", "approved"],
    aiSummary: "Structural engineering package for floors 1-40. Contains 847 drawings. Approved by PE on June 18. Key change: foundation redesign for floors 28-32.",
    status: "approved",
    category: "Engineering",
  },
  {
    id: "doc2",
    name: "Marina Complex - Construction Contract v2",
    type: "word",
    size: "1.2 MB",
    uploadedBy: "Legal Team",
    uploadedAt: "2024-03-01",
    project: "Harborview Marina Complex",
    customer: "Harborview Developments",
    tags: ["contract", "legal", "binding"],
    aiSummary: "Fixed-price contract. $4.2M with 15% retention. Penalty clause active after June 30 delay threshold. Liquidated damages: $25K/week.",
    status: "active",
    category: "Legal",
  },
  {
    id: "doc3",
    name: "I-70 Interchange - Environmental Compliance Report",
    type: "pdf",
    size: "8.3 MB",
    uploadedBy: "Diana Walsh",
    uploadedAt: "2024-05-15",
    project: "I-70 Highway Interchange",
    customer: "GreenState Infrastructure",
    tags: ["environmental", "compliance", "government"],
    aiSummary: "Full NEPA compliance confirmed. All mitigation measures implemented. No violations. Report valid for 18 months.",
    status: "approved",
    category: "Compliance",
  },
  {
    id: "doc4",
    name: "Pinnacle Resort - Change Order #7",
    type: "word",
    size: "0.8 MB",
    uploadedBy: "Sofia Nguyen",
    uploadedAt: "2024-06-18",
    project: "Pinnacle Resort Renovation",
    customer: "Pinnacle Hotels LLC",
    tags: ["change-order", "pending", "furniture"],
    aiSummary: "Change order for furniture replacement due to supplier insolvency. Additional cost: $87,000. 3-week timeline extension request.",
    status: "pending-approval",
    category: "Change Order",
  },
];

export const aiAgents = [
  {
    id: "a1",
    name: "Construction Agent",
    icon: "🏗️",
    description: "Monitors all active construction sites, analyzes progress photos, and coordinates field teams",
    status: "active",
    tasksCompleted: 1247,
    confidence: 94,
    currentTask: "Analyzing drone footage from Marina Complex site - 23% complete",
    pendingApprovals: 3,
    lastActivity: "2 min ago",
    color: "blue",
  },
  {
    id: "a2",
    name: "Finance Agent",
    icon: "💰",
    description: "Tracks all financial transactions, generates invoices, monitors cash flow and payment status",
    status: "active",
    tasksCompleted: 892,
    confidence: 97,
    currentTask: "Reconciling June expenses across 5 active projects",
    pendingApprovals: 2,
    lastActivity: "5 min ago",
    color: "emerald",
  },
  {
    id: "a3",
    name: "Customer Agent",
    icon: "👥",
    description: "Manages all customer communications, sentiment analysis, and relationship health monitoring",
    status: "active",
    tasksCompleted: 634,
    confidence: 89,
    currentTask: "Drafting escalation email for Pinnacle Hotels payment issue",
    pendingApprovals: 1,
    lastActivity: "12 min ago",
    color: "purple",
  },
  {
    id: "a4",
    name: "Reporting Agent",
    icon: "📊",
    description: "Automatically generates all project and executive reports from live data",
    status: "active",
    tasksCompleted: 418,
    confidence: 96,
    currentTask: "Generating weekly executive summary - collecting data from 18 sources",
    pendingApprovals: 4,
    lastActivity: "1 hour ago",
    color: "orange",
  },
  {
    id: "a5",
    name: "Sales Agent",
    icon: "🎯",
    description: "Identifies new opportunities, prepares quotations, and monitors lead pipeline",
    status: "idle",
    tasksCompleted: 287,
    confidence: 82,
    currentTask: "Monitoring 6 RFP portals for new opportunities",
    pendingApprovals: 0,
    lastActivity: "3 hours ago",
    color: "yellow",
  },
  {
    id: "a6",
    name: "Legal Agent",
    icon: "⚖️",
    description: "Reviews contracts, monitors compliance requirements, and flags legal risks",
    status: "active",
    tasksCompleted: 156,
    confidence: 91,
    currentTask: "Reviewing Pinnacle Hotel contract for penalty clause activation",
    pendingApprovals: 2,
    lastActivity: "30 min ago",
    color: "red",
  },
];

export const approvalQueue = [
  {
    id: "ap1",
    title: "Concrete Supplier Switch - Summit Concrete",
    category: "Procurement",
    project: "Downtown Mixed-Use Tower",
    requestedBy: "Mike Thompson",
    amount: 287400,
    status: "waiting",
    priority: "urgent",
    aiReasoning: "Current supplier failed delivery SLA. Summit Concrete meets all quality certifications. 4% price premium justified by risk mitigation. Delay cost: $45K/day.",
    confidence: 94,
    submittedAt: "1 hour ago",
    dueBy: "6 hours",
  },
  {
    id: "ap2",
    title: "Monthly Progress Report - Marina Complex",
    category: "Document",
    project: "Harborview Marina Complex",
    requestedBy: "Reporting Agent",
    amount: null,
    status: "waiting",
    priority: "high",
    aiReasoning: "Report auto-generated from 34 data sources. Contains updated risk register, progress photos, and financial summary. Client deadline: tomorrow.",
    confidence: 96,
    submittedAt: "2 hours ago",
    dueBy: "18 hours",
  },
  {
    id: "ap3",
    title: "Payment Authorization - BuilderMart Invoice #BM-8821",
    category: "Finance",
    project: "Harborview Marina Complex",
    requestedBy: "Finance Agent",
    amount: 284500,
    status: "waiting",
    priority: "medium",
    aiReasoning: "Invoice verified against PO #4492. Delivery confirmed by site supervisor. 2.1% variance within approved tolerance. Net-15 terms.",
    confidence: 88,
    submittedAt: "3 hours ago",
    dueBy: "2 days",
  },
  {
    id: "ap4",
    title: "Change Order #7 - Pinnacle Resort Furniture",
    category: "Change Order",
    project: "Pinnacle Resort Renovation",
    requestedBy: "Sofia Nguyen",
    amount: 87000,
    status: "waiting",
    priority: "high",
    aiReasoning: "Supplier insolvency is a valid force majeure event. Replacement furniture cost is market-rate. Timeline extension is necessary. Client payment risk noted.",
    confidence: 79,
    submittedAt: "5 hours ago",
    dueBy: "1 day",
  },
];

export const automationWorkflows = [
  {
    id: "wf1",
    name: "Invoice Auto-Processing",
    description: "Automatically process and route incoming invoices for approval",
    status: "active",
    runs: 1847,
    lastRun: "12 min ago",
    triggers: ["Email", "File Upload"],
    actions: ["AI Classification", "Data Extraction", "Route for Approval", "Notify Finance"],
    successRate: 97.2,
  },
  {
    id: "wf2",
    name: "Weekly Executive Report",
    description: "Auto-generate and distribute executive performance report every Monday 7AM",
    status: "active",
    runs: 52,
    lastRun: "Monday 7:00 AM",
    triggers: ["Scheduler"],
    actions: ["Collect Data", "AI Analysis", "Generate Report", "Send to CEO", "Archive"],
    successRate: 100,
  },
  {
    id: "wf3",
    name: "Risk Alert Pipeline",
    description: "Monitor project KPIs and trigger alerts when thresholds are exceeded",
    status: "active",
    runs: 24840,
    lastRun: "2 min ago",
    triggers: ["Real-time Monitor"],
    actions: ["Risk Analysis", "Alert Generation", "Assign Owner", "Escalate if Critical"],
    successRate: 99.8,
  },
  {
    id: "wf4",
    name: "New Customer Onboarding",
    description: "Automated welcome sequence and document collection for new customers",
    status: "inactive",
    runs: 23,
    lastRun: "2 weeks ago",
    triggers: ["CRM Update"],
    actions: ["Welcome Email", "Document Request", "Create Project Space", "Assign Account Manager"],
    successRate: 91.3,
  },
];

export const reports = [
  {
    id: "r1",
    title: "Executive Weekly Summary - Week 25",
    type: "weekly",
    generatedAt: "2024-06-17 07:00",
    generatedBy: "Reporting Agent",
    status: "delivered",
    recipients: ["Arjay Delos Santos (CEO)", "Board Members"],
    pages: 12,
    insights: 8,
  },
  {
    id: "r2",
    title: "Downtown Tower - Monthly Progress Report",
    type: "project",
    generatedAt: "2024-06-01 09:00",
    generatedBy: "Reporting Agent",
    status: "approved",
    recipients: ["Nexus Property Group", "Carlos Rivera"],
    pages: 24,
    insights: 5,
  },
  {
    id: "r3",
    title: "June Financial Performance Dashboard",
    type: "finance",
    generatedAt: "2024-06-20 08:00",
    generatedBy: "Finance Agent",
    status: "review",
    recipients: ["Finance Team", "CEO"],
    pages: 18,
    insights: 11,
  },
  {
    id: "r4",
    title: "Q2 Risk Assessment Report",
    type: "risk",
    generatedAt: "2024-06-30 06:00",
    generatedBy: "Reporting Agent",
    status: "scheduled",
    recipients: ["Executive Team", "Project Managers"],
    pages: 0,
    insights: 0,
  },
];

export const finances = {
  invoices: [
    { id: "inv1", number: "INV-2024-0841", customer: "GreenState Infrastructure", amount: 1240000, status: "paid", dueDate: "2024-06-01", paidDate: "2024-05-28" },
    { id: "inv2", number: "INV-2024-0842", customer: "TechPark Realty Trust", amount: 880000, status: "outstanding", dueDate: "2024-06-30", paidDate: null },
    { id: "inv3", number: "INV-2024-0843", customer: "Nexus Property Group", amount: 640000, status: "outstanding", dueDate: "2024-07-15", paidDate: null },
    { id: "inv4", number: "INV-2024-0844", customer: "Pinnacle Hotels LLC", amount: 340000, status: "overdue", dueDate: "2024-05-10", paidDate: null },
    { id: "inv5", number: "INV-2024-0845", customer: "Harborview Developments", amount: 420000, status: "paid", dueDate: "2024-06-15", paidDate: "2024-06-12" },
  ],
  budgets: [
    { project: "Downtown Mixed-Use Tower", total: 8400000, spent: 5712000, committed: 1200000, remaining: 1488000 },
    { project: "Harborview Marina Complex", total: 4200000, spent: 1890000, committed: 480000, remaining: 1830000 },
    { project: "I-70 Highway Interchange", total: 18500000, spent: 15170000, committed: 2100000, remaining: 1230000 },
    { project: "Pinnacle Resort Renovation", total: 5200000, spent: 2756000, committed: 620000, remaining: 1824000 },
    { project: "TechPark Phase 4 Campus", total: 12000000, spent: 6720000, committed: 2400000, remaining: 2880000 },
  ],
};

export const roles = [
  { id: "ceo", name: "CEO", description: "Full system access", color: "blue", user: "Arjay Delos Santos" },
  { id: "finance", name: "Finance Manager", description: "Financial modules + reports", color: "emerald", user: "Patricia Wells" },
  { id: "pm", name: "Project Manager", description: "Projects, tasks, documents", color: "purple", user: "Carlos Rivera" },
  { id: "construction", name: "Construction Manager", description: "Site operations + tasks", color: "orange", user: "Robert Chen" },
  { id: "worker", name: "Site Worker", description: "Assigned tasks only", color: "gray", user: "James Cooper" },
  { id: "customer", name: "Customer Portal", description: "Project status + invoices", color: "green", user: "David Kim (Nexus)" },
];

export const aiActivityFeed = [
  { id: "af1", agent: "Finance Agent", action: "Detected payment anomaly", detail: "Pinnacle Hotels invoice 47 days overdue", time: "2 min ago", type: "alert", icon: "💰" },
  { id: "af2", agent: "Construction Agent", action: "Analyzed site photos", detail: "Marina Complex: 24 new photos processed, progress updated", time: "8 min ago", type: "info", icon: "🏗️" },
  { id: "af3", agent: "Reporting Agent", action: "Report generated", detail: "Week 25 executive summary ready for review", time: "1 hour ago", type: "success", icon: "📊" },
  { id: "af4", agent: "Customer Agent", action: "Communication drafted", detail: "Escalation email to Pinnacle Hotels prepared", time: "1 hour ago", type: "pending", icon: "👥" },
  { id: "af5", agent: "Legal Agent", action: "Contract review", detail: "Pinnacle contract - penalty clause may activate in 5 days", time: "2 hours ago", type: "alert", icon: "⚖️" },
  { id: "af6", agent: "Construction Agent", action: "Risk assessment", detail: "Marina Complex: Critical path delay detected - 11 days", time: "3 hours ago", type: "alert", icon: "🏗️" },
];
