import { useState } from "react";
import { cn } from "@/lib/utils";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import {
  BarChart3, Sparkles, Download, RefreshCw, Clock,
  CheckCircle, Calendar, Eye,
  TrendingUp, Users, FolderKanban, DollarSign, Shield,
  AlertTriangle, Star, ChevronRight, Play
} from "lucide-react";
import { XAxis, YAxis, CartesianGrid, AreaChart, Area, Line } from "recharts";
import { ChartContainer, ChartTooltip, ChartTooltipContent } from "@/components/ui/chart";
import { reports, revenueData } from "@/lib/data";

const reportTypes = [
  { id: "all", label: "All Reports" },
  { id: "weekly", label: "Weekly" },
  { id: "monthly", label: "Monthly" },
  { id: "project", label: "Project" },
  { id: "finance", label: "Finance" },
  { id: "risk", label: "Risk" },
];

const allReports = [
  ...reports,
  {
    id: "r5", title: "Safety Compliance Report - Q2 2024",
    type: "safety", generatedAt: "2024-06-30 08:00",
    generatedBy: "Construction Agent",
    status: "scheduled", recipients: ["HSE Team", "CEO"],
    pages: 0, insights: 0,
  },
  {
    id: "r6", title: "Employee Performance Review - June",
    type: "performance", generatedAt: "2024-06-28 09:00",
    generatedBy: "Reporting Agent",
    status: "approved", recipients: ["HR", "Managers"],
    pages: 15, insights: 7,
  },
  {
    id: "r7", title: "Customer Satisfaction Analysis - H1 2024",
    type: "customer", generatedAt: "2024-06-25 10:00",
    generatedBy: "Customer Agent",
    status: "review", recipients: ["CEO", "Sales Team"],
    pages: 22, insights: 14,
  },
];

const statusConfig = {
  delivered: { badge: "bg-emerald-500/20 text-emerald-400 border-emerald-500/30", label: "Delivered" },
  approved: { badge: "bg-blue-500/20 text-blue-400 border-blue-500/30", label: "Approved" },
  review: { badge: "bg-orange-500/20 text-orange-400 border-orange-500/30", label: "Needs Review" },
  scheduled: { badge: "bg-purple-500/20 text-purple-400 border-purple-500/30", label: "Scheduled" },
  draft: { badge: "bg-muted text-muted-foreground", label: "Draft" },
};

const typeIcons: Record<string, React.ComponentType<{ className?: string }>> = {
  weekly: TrendingUp,
  monthly: Calendar,
  project: FolderKanban,
  finance: DollarSign,
  risk: AlertTriangle,
  safety: Shield,
  performance: Star,
  customer: Users,
};

interface ReportsProps {
  onNavigate: (page: string) => void;
}

const chartConfig = {
  revenue: { label: "Revenue", color: "var(--chart-1)" },
  expenses: { label: "Expenses", color: "var(--chart-5)" },
};

export function Reports({ onNavigate }: ReportsProps) {
  const [activeFilter, setActiveFilter] = useState("all");
  const [selectedReport, setSelectedReport] = useState<typeof allReports[0] | null>(null);
  const [generating, setGenerating] = useState<string | null>(null);

  const filtered = allReports.filter(r => activeFilter === "all" || r.type === activeFilter);

  const handleGenerate = (id: string) => {
    setGenerating(id);
    setTimeout(() => setGenerating(null), 2000);
  };

  return (
    <div className="space-y-4">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <h2 className="text-lg font-bold text-foreground">Reports</h2>
          <p className="text-xs text-muted-foreground">All reports auto-generated by AI · Humans review and approve</p>
        </div>
        <div className="flex items-center gap-2">
          <Button variant="outline" size="sm" className="gap-1.5 text-xs h-8"><Calendar className="w-3 h-3" />Schedule</Button>
          <Button size="sm" className="gap-1.5 text-xs h-8"><Sparkles className="w-3 h-3" />Generate New</Button>
        </div>
      </div>

      {/* Stats */}
      <div className="grid grid-cols-4 gap-3">
        {[
          { label: "Reports Generated", value: "248", sub: "This quarter", color: "text-blue-400", icon: BarChart3 },
          { label: "Pending Review", value: "3", sub: "Need approval", color: "text-orange-400", icon: Clock },
          { label: "Auto-delivered", value: "97.2%", sub: "Success rate", color: "text-emerald-400", icon: CheckCircle },
          { label: "Insights Generated", value: "1,847", sub: "Total AI insights", color: "text-purple-400", icon: Sparkles },
        ].map(s => (
          <div key={s.label} className="p-3 rounded-lg glass-subtle border-border/60 flex items-center gap-3">
            <s.icon className={cn("w-8 h-8 flex-shrink-0", s.color)} />
            <div>
              <p className={cn("text-xl font-bold", s.color)}>{s.value}</p>
              <p className="text-xs font-medium text-foreground">{s.label}</p>
              <p className="text-[10px] text-muted-foreground">{s.sub}</p>
            </div>
          </div>
        ))}
      </div>

      {/* Chart Preview */}
      <Card className="glass-subtle border-border/60">
        <CardHeader className="pb-2 pt-4 px-5">
          <div className="flex items-center justify-between">
            <CardTitle className="text-sm font-semibold text-foreground">Revenue Trend - Year to Date</CardTitle>
            <Button variant="ghost" size="sm" className="text-xs h-7 gap-1" onClick={() => onNavigate("finance")}>
              Full Report <ChevronRight className="w-3 h-3" />
            </Button>
          </div>
        </CardHeader>
        <CardContent className="px-5 pb-4">
          <ChartContainer config={chartConfig} className="h-36">
            <AreaChart data={revenueData}>
              <defs>
                <linearGradient id="revenueGrad" x1="0" y1="0" x2="0" y2="1">
                  <stop offset="5%" stopColor="var(--chart-1)" stopOpacity={0.3} />
                  <stop offset="95%" stopColor="var(--chart-1)" stopOpacity={0} />
                </linearGradient>
              </defs>
              <CartesianGrid strokeDasharray="3 3" stroke="var(--border)" />
              <XAxis dataKey="month" tick={{ fill: "var(--muted-foreground)", fontSize: 10 }} axisLine={false} tickLine={false} />
              <YAxis tick={{ fill: "var(--muted-foreground)", fontSize: 10 }} axisLine={false} tickLine={false} tickFormatter={v => `$${v / 1000000}M`} />
              <ChartTooltip content={<ChartTooltipContent />} />
              <Area type="monotone" dataKey="revenue" stroke="var(--chart-1)" fill="url(#revenueGrad)" strokeWidth={2} />
              <Line type="monotone" dataKey="expenses" stroke="var(--chart-5)" strokeWidth={2} dot={false} strokeDasharray="4 2" />
            </AreaChart>
          </ChartContainer>
        </CardContent>
      </Card>

      {/* Filters + Report List */}
      <div className="flex gap-1 mb-3">
        {reportTypes.map(t => (
          <button
            key={t.id}
            onClick={() => setActiveFilter(t.id)}
            className={cn(
              "text-[11px] px-2.5 py-1 rounded-md transition-all",
              activeFilter === t.id ? "bg-primary text-primary-foreground" : "bg-muted text-muted-foreground hover:text-foreground"
            )}
          >
            {t.label}
          </button>
        ))}
      </div>

      <div className="grid grid-cols-3 gap-3">
        {filtered.map(report => {
          const TypeIcon = typeIcons[report.type] || BarChart3;
          const status = statusConfig[report.status as keyof typeof statusConfig];
          const isGenerating = generating === report.id;
          return (
            <Card
              key={report.id}
              className={cn(
                "glass-subtle border-border/60 cursor-pointer hover:border-border transition-all",
                selectedReport?.id === report.id && "border-primary/40"
              )}
              onClick={() => setSelectedReport(report)}
            >
              <CardContent className="p-4">
                <div className="flex items-start justify-between mb-3">
                  <div className="w-9 h-9 rounded-lg bg-primary/15 flex items-center justify-center flex-shrink-0">
                    <TypeIcon className="w-4 h-4 text-primary" />
                  </div>
                  <Badge className={cn("text-[9px] border", status?.badge || "bg-muted text-muted-foreground")}>
                    {status?.label}
                  </Badge>
                </div>

                <h3 className="text-xs font-semibold text-foreground line-clamp-2 mb-1">{report.title}</h3>
                <p className="text-[10px] text-muted-foreground mb-2">By {report.generatedBy}</p>

                {report.pages > 0 && (
                  <div className="flex items-center gap-3 text-[10px] text-muted-foreground mb-3">
                    <span>{report.pages} pages</span>
                    <span>·</span>
                    <span className="flex items-center gap-0.5 text-primary"><Sparkles className="w-2.5 h-2.5" />{report.insights} insights</span>
                  </div>
                )}

                <div className="flex items-center gap-2">
                  {report.status === "review" && (
                    <Button size="sm" className="flex-1 text-xs h-6 bg-emerald-600 hover:bg-emerald-700 text-white" onClick={e => { e.stopPropagation(); }}>
                      Approve
                    </Button>
                  )}
                  {report.status === "scheduled" && (
                    <Button size="sm" variant="outline" className="flex-1 text-xs h-6 gap-1"
                      onClick={e => { e.stopPropagation(); handleGenerate(report.id); }}>
                      {isGenerating ? <RefreshCw className="w-2.5 h-2.5 animate-spin" /> : <Play className="w-2.5 h-2.5" />}
                      {isGenerating ? "Generating..." : "Generate Now"}
                    </Button>
                  )}
                  {(report.status === "delivered" || report.status === "approved") && (
                    <>
                      <Button size="sm" variant="outline" className="flex-1 text-xs h-6 gap-1">
                        <Eye className="w-2.5 h-2.5" />View
                      </Button>
                      <Button size="sm" variant="ghost" className="h-6 w-6 p-0" onClick={e => { e.stopPropagation(); handleGenerate(report.id); }}>
                        {isGenerating ? <RefreshCw className="w-3 h-3 animate-spin" /> : <RefreshCw className="w-3 h-3" />}
                      </Button>
                    </>
                  )}
                  {report.status !== "review" && report.status !== "scheduled" && (
                    <Button size="sm" variant="ghost" className="h-6 w-6 p-0">
                      <Download className="w-3 h-3" />
                    </Button>
                  )}
                </div>
              </CardContent>
            </Card>
          );
        })}
      </div>
    </div>
  );
}
